<?php

namespace MLBBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MLBGameScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MLBGameScheduleRepository extends EntityRepository
{
}
